version: '3'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    networks:
      - conquerer-network
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 
      POSTGRES_DB: conquerer
    ports:
      - "5432:5432"
    networks:
      - conquerer-network
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - conquerer-network
networks:
  conquerer-network:
    external: true